apiVersion: v1
kind: Service
metadata:
  name: vite-react-app-service
  labels:
    app: vite-react-app
spec:
  type: NodePort
  selector:
    app: vite-react-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
